### ISSUE TITLE
Install and launch on Synology

### ISSUE THREAD

**Issue by silenzi71** [peerdavid/remapy#26]
Hi,
I've tried to follow the installation steps provided, to have the application running from a Synology NAS.
Before that, I've checked that Python3, Pip and tkinter were installed on my NAS.
Then I put the directory inside a shared folder, and launched the install.sh script.
Apparently, there is no activation file in the env/bin directory, so that call failed; all the rest run properly.
Of course, the launch fails, because the activation call goes wrong, as well.

It also seems that tkinter does not run properly on my system.

Have you heard about this issues? Is there a way to overcome them? I've tried with the superuser account too, with no avail

I chose to try with the NAS, because the Windows 10 option is not working as well.

Thanks,
Andrea

**Comment by silenzi71** [comment]
I think to have solved the virtualenv issue, and the installations script now ends without issues.
Still, tkinter continues not to be imported in python3, and this stops the launch script to run

**Comment by peerdavid** [comment]
Hello,

can you try if this helps to solve your tkinter problem:
https://github.com/peerdavid/remapy/wiki/FAQ

David

**Comment by peerdavid** [comment]
I will close this issue as there is no progress. Feel free to reopen it if it is still a problem.
