### ISSUE TITLE
Error ImageTK

### ISSUE THREAD

**Issue by andrelec1** [peerdavid/remapy#28]
I'm on ubuntu mate 20.4 ...

I just clone the repo, lunch the install.sh , then the lunch.sh ...

I got this error : 

```
Traceback (most recent call last):
  File "./rema.py", line 10, in <module>
    from gui.file_explorer import FileExplorer
  File "/home/andrelec1/Documents/remapy/gui/file_explorer.py", line 17, in <module>
    from PIL import ImageTk as itk
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
```

**Comment by andrelec1** [comment]
`apt-get install python3-pil.imagetk` fix the issue 
 
 ( so fix the install.sh or provide information in the readme ;) )

**Comment by peerdavid** [comment]
Thanks, added to https://github.com/peerdavid/remapy/wiki/FAQ as it seems that this installation is not necessary for all systems.
