### ISSUE TITLE
Switch account

### ISSUE THREAD

**Issue by ZacharieALES** [peerdavid/remapy#29]
Hello,

Is it possible to switch the remarkable account managed by remapy?

Even if it requires to move files I would be interested in a way to reset remapy in order to log in with another account.
I tried to install it in another directory but it is not that easy ^^.

**Comment by peerdavid** [comment]
No sry I never considered this case. To work with two different accounts in two directories you have to adapt the occurrences of ".remapy" within the code of the second remapy directory to ".remapy_2" - then you can use two accounts...  It should occur two times, one time in utils.py and one time in item.py

**Comment by ZacharieALES** [comment]
Thank you for your answer. No problem at all :).

To be sure I understood, what I need to do is:
- clone the git project in another directory;
- replace in the files of this directory all occurrences of ".remapy" by ".remapy_2".
Am I correct?

**Comment by peerdavid** [comment]
Yea exactly - everything is stored per default into the .remapy folder. If you change this to .remapy_2 it should be possible to use two accounts...

**Comment by peerdavid** [comment]
I will close this issue due to inactivity. Feel free to reopen it :)

**Comment by ZacharieALES** [comment]
Oh no problem, I forgot to keep you up to date.

I tested it a few days ago. I can see the files in my cloud but I was not able to add a file to the cloud.
If I drag an drop a pdf file nothing happened. If try a second time with the same file I have a message which says that the file already exists (however, the pdf does not appear in the file list and it is not uploaded on any of my two rMs).

Do you have any idea why?

**Comment by peerdavid** [comment]
Drag and drop is not implemented yet. Instead you can copy in your file explorer and paste in remapy...

**Comment by ZacharieALES** [comment]
Indeed, my bad...

It works, thank you!
