### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by fvirdia** [peerdavid/remapy#3]
Hi There,

I had put out a while ago a small python desktop client, which I recently worked to upgrade. You can find it [here](https://github.com/fvirdia/remar). I'm guessing from your commit history that the lockdown may have had the same effect on both of us, ha!

Since collaboration is often better than not, I was wondering if you'd be interested in joining forces. Although maybe having multiple people push with self-made implementations of the client may get the reMarkable people to re-release theirs for Linux.

**Comment by peerdavid** [comment]
Hi,

yes you are right, the lockdown had the same effect on both of us :)

remar looks really nice and I agree that a collaboration would be advantageous, but honestly I'm not sure how we can collaborate because remar is an electron app right? My idea was to write it to 100% in Python because I already had some code especially for the rendering and annotations of pdf's...

**Comment by fvirdia** [comment]
Agreed, the stack is quite different. I wanted to try out your rendering of annotations cause it would be an interesting port. I also read of some python2js compilers out there, that I could look into. If you are interested, I can provide you the queries for bookmarking/moving, though they are exactly what one would expect.

**Comment by peerdavid** [comment]
> Agreed, the stack is quite different. I wanted to try out your rendering of annotations cause it would be an interesting port. I also read of some python2js compilers out there, that I could look into. 

Yea the rendering of annotations is really interesting and I think really challenging if it should be to 100% similar than on the rm tablet. For example the pencil still looks totally different if its generated with remapy than on the rm tablet or on the android app... For the python2js compiler would this also work for the libraries that I use there (reportlab, pdfrw)? 

> If you are interested, I can provide you the queries for bookmarking/moving, though they are exactly what one would expect.
Thank you, I think I use the same query as https://github.com/subutux/rmapy or is it wrong?

**Comment by peerdavid** [comment]
I willl close this issue now due to inactivity. Feel free to reopen this issue or contact me at any time.
