### ISSUE TITLE
Feature request: Page size adjustment

### ISSUE THREAD

**Issue by phiste** [peerdavid/remapy#34]
First of all, big thanks for this handy tool!

I want to suggest a feature that would improve usability of uploaded pdfs with annotations. Currently, it seems that the rendering engine keeps the original page size for all pdfs, even though the ReMarkable allows annotations to be made on the space beyond that. This results in annotations sometimes being unreadable in the remapy-generated files as they are outside of the original page borders. Would it perhaps be possible to automatically enlarge the page size for annotated pdfs so that annotations are guaranteed to be visible?

[The original ReMarkable rendering enlarges pages whenever annotations go beyond the original page size]

**Comment by peerdavid** [comment]
Should be implemented now.
