### ISSUE TITLE
Render Templates

### ISSUE THREAD

**Issue by popa13** [peerdavid/remapy#36]
I really like to use templates on my Remarkable. I have noticed recently that it is not rendered in the PDF files in ReMapy. Is it something you had in your roadmap or you had in mind to implement? If not, would it be difficult to modify the source code to make it work? You can contact me by email at pierre_olivierp@hotmail.ca (webpage mathopo.ca).

Thank you very much!
Pierre-Olivier Parisé

**Comment by peerdavid** [comment]
Hello,
Templates, as well as custom templates, are already supported. But you have to manually download the template files (png) from your ReMarkable tablet and store it somewhere on your PC - I simply can not distribute the templates via github - this is the property of ReMarkable and it would not be legal for me to publish and distribute those files... 
After you downloaded the templates simply set the path in RemaPy -> Settings -> General -> Templates path. To render all pdf files again (rendering is triggered only if something changes) click the "ReSync" button.

I hope this helps :)

David
