### ISSUE TITLE
Feature Request: rmfakecloud support

### ISSUE THREAD

**Issue by nzbcorz** [peerdavid/remapy#38]
Hi. I noticed that `api/remarkable_client.py` defines the api url of remarkable server.

So I wonder that if changing this could support ddck's [rmfakecloud](https://github.com/ddvk/rmfakecloud) or add a feature that server-url could be changed through GUI.

Thanks!

**Comment by peerdavid** [comment]
I really don't know as I never tested the rmfakecloud and I will probably not test this in the near future. But if the API is the same then changing the URLs in ```remarkable_client.py``` should indeed be enough to redirect all requests.

David

**Comment by nzbcorz** [comment]
I texted. Tho few problems still occur but it worked.

**Comment by peerdavid** [comment]
Great to hear - I will close this issue now as currently an explicit rmfakecloud support is not the focus of this app.
