### ISSUE TITLE
launch.sh: 4: Bad substitution

### ISSUE THREAD

**Issue by sabrekke** [peerdavid/remapy#39]
Hi,

I tried reinstalling remapy today, after encountering a problem described in pull request 20. However, running launch.sh returns the following: 

`launch.sh: 4: Bad substitution`

install.sh returns:
`install.sh: 4: source: not found
Defaulting to user installation because normal site-packages is not writeable`
followed by a list of satisfied requirements. 

The old installation of Remapy still opens, but the file explorer is not rendering (and files do not appear to be synced).

I'm on Ubuntu 21.04.

**Comment by peerdavid** [comment]
There is a problem with authentication such that nothing is rendered. I just fixed this. Please pull again and try it one more time.

**Comment by peerdavid** [comment]
Also, can you elaborate a bit more why and how your problem is related to the scaling or HDMI of the application i.e. PR #20? Because my changes are totally unrelated to PR 20 and I don't want to merge this right now which would mean that your problem will not be resolved.

**Comment by sabrekke** [comment]
You're right - it works perfectly after pulling again. Thank you.

I was just confused by the fact that my problems matched your description of the file browser failing to load in PR #20, since I had made some changes to work with a hdpi display myself. Causal inference is hard!

**Comment by peerdavid** [comment]
Ah ok I understand - great that it works now!
