### ISSUE TITLE
(Warning) Failed to publish subscriber. 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by popa13** [peerdavid/remapy#40]
Hi,
I have gone through the following issue : 
(Warning) Failed to publish subscriber.
'NoneType' object is not iterable

I was wondering if I can do something because, right now, I can't sync the Remarkable tablet files to the Remapy app. 

Thank you for your help!
Pierre

**Comment by peerdavid** [comment]
I just fixed this issue, please pull the code again :)

**Comment by popa13** [comment]
Ahahah zut. I have disconnected my remarkable and now I got a Could not renew user token (please try again). I have pulled the code again. Can I change the state of One-time-Code's text field to normal?

Pierre

**Comment by peerdavid** [comment]
simply delete the config file HOME/.remapy/config

**Comment by popa13** [comment]
Thank you very much again! Working like a charm :)

**Comment by peerdavid** [comment]
Cool that it works again 👍🏻😃
