### ISSUE TITLE
Error Syncing Notebooks

### ISSUE THREAD

**Issue by jmrojash** [peerdavid/remapy#41]
I have just updated remapy and noticed that even though the annotated PDFs synced fine, there are problems syncing notebooks, even the notebook "Quick sheets" does not sync.

I use remapy in Windows, and in CMD the message that appears for each notebook I have in my reMarkable is:

**_stat: path should be string, bytes, os.PathLike or integer, not NoneType_**

Also, I have a similar problem when trying remapy in Ubuntu

**Comment by ben-no** [comment]
I have the same issue.

**Comment by peerdavid** [comment]
Can you please pull the latest version and test the sync again?

**Comment by jmrojash** [comment]
It works now! The latest version solved the problem.

Thank you!

**Comment by peerdavid** [comment]
Great! I will close this issue now. Feel free to open it again ...
