### ISSUE TITLE
Offline mode?

### ISSUE THREAD

**Issue by drewsed** [peerdavid/remapy#42]
Hi,
in the readme there is a offline mode mentioned in the section "Other Features".
Well, I am not able to do anything inside the app without putting in a one-time-code ... could someone guide me on how to use the app offline only?

Thanks in advance

**Comment by peerdavid** [comment]
Hello,

the offline mode means that you can view the latest synced version if no connection to the cloud exists. A ssh mode to upload and download files directly from the rm tablet is not supported. There are different tools such as RCU (http://www.davisr.me/projects/rcu/) for that.

I hope this helps, 
David

**Comment by drewsed** [comment]
Hi David,
thanks for the explanation.
I am interested in using my rm tablet completely without the cloud, so i will look into other options before buying RCU. 

But nevertheless: Great work!
