### ISSUE TITLE
how to generate one-time code

### ISSUE THREAD

**Issue by pagism** [peerdavid/remapy#43]
I am trying to run remapy from linux, explorer starts but I cannot figure out how to generate one-time code in general, the reMarkable site does not have much info either, any hints on that?
thanks

**Comment by peerdavid** [comment]
Simply open https://my.remarkable.com/device/connect/desktop with your browser and enter the code that is displayed in RemaPy

**Comment by peerdavid** [comment]
Update: I also updated the link in RemaPy.

**Comment by pagism** [comment]
Thanks for the update, it works ok now.  One issue I noticed that I had to install manually python3-tk as it was not installed by default on my system.
thanks again

**Comment by peerdavid** [comment]
Thank you very much!
