### ISSUE TITLE
remapy crashes x server (dwm) upon opening new window

### ISSUE THREAD

**Issue by ctdunc** [peerdavid/remapy#44]
to replicate:
running the dwm window manager, and using st, open remapy, and then open an st  instance. This causes the xserver to become unresponsive and require a force quit and full restart. 

Source is installed in `~/.local/src/remapy`, and symlinked to my path at `~/.local/lib/remapy -> ~/.local/src/remapy/launch.sh`.

I am unsure where to find the log output, but will post that if I can find it. Thanks!

**Comment by peerdavid** [comment]
Hi,

if you start remaPy in the console you should see a log output... Never had a crash until now - but as far as I know this also happens with MacOS.

David

**Comment by peerdavid** [comment]
I will close this issue now due to inactivity - feel free to reopen it.
