### ISSUE TITLE
Error upon installing (env/bin/activate)

### ISSUE THREAD

**Issue by vchryssos** [peerdavid/remapy#51]
Hi there, 
When I execute install.sh I get the following error: 
`./install.sh: line 4: env/bin/activate: No such file or directory`

I checked /env/bin and there's no `activate` file in there. 

Can you help? 

Thank you!

**Comment by peerdavid** [comment]
Can you please try to rm the env folder and execute line 3 of the script? seems that the virtual environment was not created...

David

**Comment by axkibe** [comment]
```
python3 -m venv env
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/axel/remapy/env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

```
I guess thats the same what happened here

**Comment by axkibe** [comment]
You may want to catch errors when calling that line
