### ISSUE TITLE
Problems syncing with Remarkable Version 2.11 and colours

### ISSUE THREAD

**Issue by Konrad982** [peerdavid/remapy#54]
The Remarkable version 2.11 software update introduces colours. Documents with colours fail to sync.

**Comment by peerdavid** [comment]
Thanks for the bug report. Unfortunately, not enough information is provided to fix the bug as my own device is not updated yet.

**Comment by Konrad982** [comment]
What information would you need?
I attach some screenshots to show you all the stroke options available for each type of pen after the update.

Information on the screenshots:
Screenshots are made with https://github.com/bordaigorl/rmview after applying the fix https://github.com/bordaigorl/rmview/issues/117 in order to make colours visible as colours. On the remarkable itself, colours are displayed as shades of grey. I thought it may be helpful to know that rmview can in principle deal with colours.

![rm-screenshot](https://user-images.githubusercontent.com/34189408/146021678-e96c5e57-22d1-4500-bcf6-2b8594afdce2.png)
![rm-screenshot2](https://user-images.githubusercontent.com/34189408/146021682-ac5f9ffa-b815-4242-90a1-a4a0a5d39293.png)
![rm-screenshot3](https://user-images.githubusercontent.com/34189408/146021683-4cc4e823-4261-49c6-8446-028537d7f002.png)
![rm-screenshot4](https://user-images.githubusercontent.com/34189408/146021686-fc754eff-b641-4e02-b366-13c82c208302.png)
![rm-screenshot5](https://user-images.githubusercontent.com/34189408/146021688-6bf2525b-e110-4498-ac36-338eaa75a094.png)
![rm-screenshot6](https://user-images.githubusercontent.com/34189408/146021689-c54d558b-8128-49c5-a9fa-40500c03d415.png)
![rm-screenshot7](https://user-images.githubusercontent.com/34189408/146021691-b561d13d-ae3d-4436-a6bc-8940e0cbfeca.png)
![rm-screenshot8](https://user-images.githubusercontent.com/34189408/146021693-bf5d4f82-016a-42a3-b0cd-04d61b6d6464.png)

**Comment by Konrad982** [comment]
UPDATE: Adding some dummy entries to the `default_stroke_color` dictionary in `render.py` prevents the sync from failing. However, it does not get the colors right yet. I think I might be able to solve that myself and add a pull request in the next days.
`default_stroke_color = {
    0: (0 / 255., 0 / 255., 0 / 255.),        # Pen color 1
    1: (100 / 255., 100 / 255., 100 / 255.),        # Pen color 2
    2: (255 / 255., 255 / 255., 255 / 255.),      # Eraser
    3: (255 / 255., 255 / 255., 0),               # Highlighter
    4: (50 / 255., 50 / 255., 50 / 255.),          # Pencil
    5: (50 / 255., 50 / 255., 255 / 255.),
    6: (50 / 255., 50 / 255., 255 / 255.),
    7: (255 / 255., 50 / 255., 50 / 255.),
    8: (50 / 255., 50 / 255., 50 / 255.),
    9: (50 / 255., 50 / 255., 50 / 255.),
    10: (50 / 255., 50 / 255., 50 / 255.),
    11: (50 / 255., 50 / 255., 50 / 255.),
    12: (50 / 255., 50 / 255., 50 / 255.),
    13: (50 / 255., 50 / 255., 50 / 255.)
}`

**Comment by peerdavid** [comment]
Wow thank you so much for debugging and fixing - you are totally correct to add default stroke colors. Now we have to find the correct RGB values. In past, I simply used blue instead of black, but probably its better now to also adjust pen color 1 :)

**Comment by Konrad982** [comment]
I just added a pull request that adds the colors and also renders highlighters first.

**Comment by peerdavid** [comment]
Should be solved now.
