### ISSUE TITLE
evince not installed on every system

### ISSUE THREAD

**Issue by lschneiderbauer** [peerdavid/remapy#6]
Just a minor thing:
Your script seems to want to open all pdf files with evince. If it's not installed, the browser does nothing instead. Why not use xdg-open for pdf files as well, as you do for other files?

**Comment by peerdavid** [comment]
Hi,

thanks for your comment. I will check if evince is installed and use xdg-open as fallback. I prefer evince, because I can open the same page that is currently opened on the remarkable tablet via `evince -i`

**Comment by lschneiderbauer** [comment]
That sounds reasonable.

Btw: Thank you for putting time into this project! It's very useful, at least to me.

**Comment by peerdavid** [comment]
> That sounds reasonable.
> 
> Btw: Thank you for putting time into this project! It's very useful, at least to me.

You're welcome :) 
The bug should be fixed with the latest commit, therefore I close this issue. Feel free to reopen it.
