### ISSUE TITLE
Explorer only shows some of the files

### ISSUE THREAD

**Issue by hohu05** [peerdavid/remapy#7]
Hi,
thank you for your work. I'd like to use remapy regularly under linux, but the explorer only shows some of the files although I can find every file by setting filters.
Is this a bug?

**Comment by peerdavid** [comment]
All top level files and collections should be shown also without using a filter, *but* all collections are collapsed if no filter is set (the filter expands collections). Have you also tried to expand the collection which should contain the file by double clicking it?

**Comment by hohu05** [comment]
After starting the program, only some files show up (the last files in alphabetic order, I think). When I set the filter to two letters the directories and files containing these letters show up.
Starting the program I see the following output on the console:
`(Warning) Failed to publish subscriber.
year 0 is out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/ho/reMarkable/remapy/gui/file_explorer.py", line 215, in filter_changed_event_handler
    self._update_tree(root, filter_text)
  File "/home/ho/reMarkable/remapy/gui/file_explorer.py", line 240, in _update_tree
    self._update_tree(child, filter)
  File "/home/ho/reMarkable/remapy/gui/file_explorer.py", line 229, in _update_tree
    self._update_tree_item(item)
  File "/home/ho/reMarkable/remapy/gui/file_explorer.py", line 300, in _update_tree_item
    item.modified_time().strftime("%Y-%m-%d %H:%M:%S"),
  File "/home/ho/reMarkable/remapy/model/item.py", line 98, in modified_time
    offset = datetime.fromtimestamp(epoch) - datetime.utcfromtimestamp(epoch)`

**Comment by peerdavid** [comment]
It seems that one document is corrupt i.e. the datetime of this document is invalid. I pushed a fix such that 01/01/1970 is shown for this document or if also other parameters are wrong only this document is removed from the tree view. All other files should still be shown.

Can you please pull the changes and check if your problem is fixed?

**Comment by hohu05** [comment]
Everything seems to work fine now.
Thank you!
