### ISSUE TITLE
Execution failed

### ISSUE THREAD

**Issue by zelomel** [peerdavid/remapy#8]
Hi,

I installed remapy for the first time today. I followed installation instructions. The first issue I got was `Could not build wheels for pyyaml, since package 'wheel' is not installed` so I added "wheel" to "requirements.txt".  After that it seemed to be ok but I obtained :
`raceback (most recent call last):
  File "./rema.py", line 5, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
`

Now, I don't know how to do anymore... Could you help me?

Laurent

**Comment by zelomel** [comment]
OK, I solved my problem. Tkinter was not installed. I followed these instructions : http://www.greenteapress.com/thinkpython/swampy/install.html

**Comment by peerdavid** [comment]
Thanks for your input - I will add wheels to the requirements.txt and I will add the problem with tkinter to the FAQ section as it should be shipped with Python (https://www.tutorialspoint.com/python3/python_gui_programming.htm).

**Comment by zelomel** [comment]
I'm using ubuntu 18.04 in a VM. Maybe installation is a little bit different.

Another question : to restart rema.py, I have to enter
`python3 -m venv env
source env/bin/activate
./rema.py`

and not only
`./rema.py`

Is it normal ?

By the way, great job ! It is very useful and easy to use.

Laurent

**Comment by peerdavid** [comment]
> I'm using ubuntu 18.04 in a VM. Maybe installation is a little bit different.
> 
> Another question : to restart rema.py, I have to enter
> `python3 -m venv env`
> `source env/bin/activate`
> `./rema.py`
> 
> and not only
> `./rema.py`
> 
> Is it normal ?
> 
> By the way, great job ! It is very useful and easy to use.
> 
> Laurent

Thank you :) Yes its normal if packages are installed in an environment (which you normally do for development). You can also install the references system wide then ./rema.py should be enough to start remapy. See also https://github.com/peerdavid/remapy/wiki/Install

David

**Comment by zelomel** [comment]
My knowledge in Linux machine is limited. I don't know how to install the references system wide.
I created a  bash script with the two necessary lines and I made it executable. It works fine for me.

Laurent

**Comment by zelomel** [comment]
My knowledge in Linux machine is limited. I don't know how to install the references system wide.
I created a  bash script with the two necessary lines and I made it executable. It works fine for me.

Laurent
